spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/appointment_system
spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.jpa.hibernate.ddl-auto=update
jwt.key.key=ZmZkZmRzamtrZHNua2R2ZmQdddddddaxvesxsyMmRmZGZtdjIzcw== 
jwt.access-token-expiration.expiration=36000000
jwt.refresh-token-expiration.expiration=604800000
# === Google OAuth2 Config ===
spring.security.oauth2.client.registration.google.client-id=686828999869-2l6hubtd8g3i0p8ee0lq2fsp1uh8npep.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile,openid,https://www.googleapis.com/auth/calendar.events
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo



